"""sync database

Revision ID: 4c8f0df852f0
Revises: 
Create Date: 2026-04-05 15:47:35.570356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8f0df852f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_filters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match', sa.Text(), nullable=False),
    sa.Column('replacement', sa.Text(), nullable=False),
    sa.Column('block', sa.Boolean(), nullable=False),
    sa.Column('whitespace_delimited', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchmaking_pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('lobby_size', sa.Integer(), nullable=False),
    sa.Column('rating_search_radius', sa.Integer(), nullable=False),
    sa.Column('rating_search_radius_max', sa.Integer(), nullable=False),
    sa.Column('rating_search_radius_exp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osu_builds',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('hash', sa.LargeBinary(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('allow_bancho', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('build_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('country_acronym', sa.String(length=2), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('playmode', sa.Enum('OSU', 'TAIKO', 'CATCH', 'MANIA', name='gamemode'), nullable=False),
    sa.Column('playstyle', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_supporter', sa.Boolean(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('hide_presence', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_pm_from_non_friends', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_visit', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('beatmapsets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('artist_unicode', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_unicode', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('GRAVEYARD', 'WIP', 'PENDING', 'RANKED', 'APPROVED', 'QUALIFIED', 'LOVED', name='beatmapstatus'), nullable=False),
    sa.Column('ranked_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('favourite_count', sa.Integer(), nullable=False),
    sa.Column('preview_url', sa.String(length=512), nullable=True),
    sa.Column('covers', sa.Text(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=False),
    sa.Column('has_storyboard', sa.Boolean(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('spotlight', sa.Boolean(), nullable=False),
    sa.Column('discussion_locked', sa.Boolean(), nullable=False),
    sa.Column('download_disabled', sa.Boolean(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beatmapsets_status'), 'beatmapsets', ['status'], unique=False)
    op.create_table('matchmaking_user_elo_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('elo_before', sa.Integer(), nullable=False),
    sa.Column('elo_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['matchmaking_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchmaking_user_elo_history_opponent_id'), 'matchmaking_user_elo_history', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_matchmaking_user_elo_history_pool_id'), 'matchmaking_user_elo_history', ['pool_id'], unique=False)
    op.create_index(op.f('ix_matchmaking_user_elo_history_user_id'), 'matchmaking_user_elo_history', ['user_id'], unique=False)
    op.create_table('matchmaking_user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('first_placements', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('elo_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['matchmaking_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pool_id'),
    sa.UniqueConstraint('user_id', 'pool_id', name='uq_matchmaking_user_stats_user_pool')
    )
    op.create_table('multiplayer_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('queue_mode', sa.String(length=32), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('auto_start_duration', sa.Integer(), nullable=False),
    sa.Column('auto_skip', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('current_playlist_item_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('redirect', sa.Text(), nullable=False),
    sa.Column('personal_access_client', sa.Boolean(), nullable=False),
    sa.Column('password_client', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('user_relations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('friend', sa.Boolean(), nullable=False),
    sa.Column('foe', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'target_id')
    )
    op.create_table('user_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('OSU', 'TAIKO', 'CATCH', 'MANIA', name='gamemode'), nullable=False),
    sa.Column('ranked_score', sa.BigInteger(), nullable=False),
    sa.Column('total_score', sa.BigInteger(), nullable=False),
    sa.Column('pp', sa.Float(), nullable=False),
    sa.Column('global_rank', sa.BigInteger(), nullable=True),
    sa.Column('country_rank', sa.BigInteger(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('hit_accuracy', sa.Float(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('play_time', sa.Integer(), nullable=False),
    sa.Column('total_hits', sa.BigInteger(), nullable=False),
    sa.Column('maximum_combo', sa.Integer(), nullable=False),
    sa.Column('replays_watched', sa.Integer(), nullable=False),
    sa.Column('grade_ss', sa.Integer(), nullable=False),
    sa.Column('grade_ssh', sa.Integer(), nullable=False),
    sa.Column('grade_s', sa.Integer(), nullable=False),
    sa.Column('grade_sh', sa.Integer(), nullable=False),
    sa.Column('grade_a', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_statistics_mode'), 'user_statistics', ['mode'], unique=False)
    op.create_index(op.f('ix_user_statistics_user_id'), 'user_statistics', ['user_id'], unique=False)
    op.create_table('beatmaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beatmapset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.Enum('OSU', 'TAIKO', 'CATCH', 'MANIA', name='gamemode'), nullable=False),
    sa.Column('status', sa.Enum('GRAVEYARD', 'WIP', 'PENDING', 'RANKED', 'APPROVED', 'QUALIFIED', 'LOVED', name='beatmapstatus'), nullable=False),
    sa.Column('cs', sa.Float(), nullable=False),
    sa.Column('ar', sa.Float(), nullable=False),
    sa.Column('od', sa.Float(), nullable=False),
    sa.Column('hp', sa.Float(), nullable=False),
    sa.Column('difficulty_rating', sa.Float(), nullable=False),
    sa.Column('total_length', sa.Integer(), nullable=False),
    sa.Column('hit_length', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('count_circles', sa.Integer(), nullable=False),
    sa.Column('count_sliders', sa.Integer(), nullable=False),
    sa.Column('count_spinners', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('max_combo', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beatmapset_id'], ['beatmapsets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beatmaps_beatmapset_id'), 'beatmaps', ['beatmapset_id'], unique=False)
    op.create_index(op.f('ix_beatmaps_checksum'), 'beatmaps', ['checksum'], unique=False)
    op.create_index(op.f('ix_beatmaps_difficulty_rating'), 'beatmaps', ['difficulty_rating'], unique=False)
    op.create_index(op.f('ix_beatmaps_mode'), 'beatmaps', ['mode'], unique=False)
    op.create_index(op.f('ix_beatmaps_status'), 'beatmaps', ['status'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_beatmap_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beatmapset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beatmapset_id'], ['beatmapsets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'beatmapset_id')
    )
    op.create_table('kudosu_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beatmap_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmaps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kudosu_history_created_at'), 'kudosu_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_kudosu_history_user_id'), 'kudosu_history', ['user_id'], unique=False)
    op.create_table('matchmaking_pool_beatmaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('beatmap_id', sa.Integer(), nullable=False),
    sa.Column('mods', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('selection_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['matchmaking_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchmaking_pool_beatmaps_beatmap_id'), 'matchmaking_pool_beatmaps', ['beatmap_id'], unique=False)
    op.create_index(op.f('ix_matchmaking_pool_beatmaps_pool_id'), 'matchmaking_pool_beatmaps', ['pool_id'], unique=False)
    op.create_table('multiplayer_playlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('beatmap_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('required_mods', sa.Text(), nullable=False),
    sa.Column('allowed_mods', sa.Text(), nullable=False),
    sa.Column('playlist_order', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['multiplayer_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiplayer_playlist_items_room_id'), 'multiplayer_playlist_items', ['room_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beatmap_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('total_score', sa.BigInteger(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('pp', sa.Float(), nullable=True),
    sa.Column('max_combo', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=4), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('ranked', sa.Boolean(), nullable=False),
    sa.Column('preserve', sa.Boolean(), nullable=False),
    sa.Column('has_replay', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unix_updated_at', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('legacy_score_id', sa.BigInteger(), nullable=True),
    sa.Column('legacy_total_score', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_beatmap_id'), 'scores', ['beatmap_id'], unique=False)
    op.create_index(op.f('ix_scores_ended_at'), 'scores', ['ended_at'], unique=False)
    op.create_index(op.f('ix_scores_passed'), 'scores', ['passed'], unique=False)
    op.create_index(op.f('ix_scores_ruleset_id'), 'scores', ['ruleset_id'], unique=False)
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('beatmap_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('OSU', 'TAIKO', 'CATCH', 'MANIA', name='gamemode'), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmaps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_type'), 'user_activities', ['type'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('multiplayer_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('playlist_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.BigInteger(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('pp', sa.Float(), nullable=True),
    sa.Column('max_combo', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=4), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playlist_item_id'], ['multiplayer_playlist_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['multiplayer_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiplayer_scores_playlist_item_id'), 'multiplayer_scores', ['playlist_item_id'], unique=False)
    op.create_index(op.f('ix_multiplayer_scores_room_id'), 'multiplayer_scores', ['room_id'], unique=False)
    op.create_index(op.f('ix_multiplayer_scores_user_id'), 'multiplayer_scores', ['user_id'], unique=False)
    op.create_table('score_process_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_process_history_score_id'), 'score_process_history', ['score_id'], unique=True)
    op.create_table('score_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beatmap_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('playlist_item_id', sa.Integer(), nullable=True),
    sa.Column('score_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_item_id'], ['multiplayer_playlist_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_tokens_beatmap_id'), 'score_tokens', ['beatmap_id'], unique=False)
    op.create_index(op.f('ix_score_tokens_playlist_item_id'), 'score_tokens', ['playlist_item_id'], unique=False)
    op.create_index(op.f('ix_score_tokens_user_id'), 'score_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_tokens_user_id'), table_name='score_tokens')
    op.drop_index(op.f('ix_score_tokens_playlist_item_id'), table_name='score_tokens')
    op.drop_index(op.f('ix_score_tokens_beatmap_id'), table_name='score_tokens')
    op.drop_table('score_tokens')
    op.drop_index(op.f('ix_score_process_history_score_id'), table_name='score_process_history')
    op.drop_table('score_process_history')
    op.drop_index(op.f('ix_multiplayer_scores_user_id'), table_name='multiplayer_scores')
    op.drop_index(op.f('ix_multiplayer_scores_room_id'), table_name='multiplayer_scores')
    op.drop_index(op.f('ix_multiplayer_scores_playlist_item_id'), table_name='multiplayer_scores')
    op.drop_table('multiplayer_scores')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_type'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_ruleset_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_passed'), table_name='scores')
    op.drop_index(op.f('ix_scores_ended_at'), table_name='scores')
    op.drop_index(op.f('ix_scores_beatmap_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_multiplayer_playlist_items_room_id'), table_name='multiplayer_playlist_items')
    op.drop_table('multiplayer_playlist_items')
    op.drop_index(op.f('ix_matchmaking_pool_beatmaps_pool_id'), table_name='matchmaking_pool_beatmaps')
    op.drop_index(op.f('ix_matchmaking_pool_beatmaps_beatmap_id'), table_name='matchmaking_pool_beatmaps')
    op.drop_table('matchmaking_pool_beatmaps')
    op.drop_index(op.f('ix_kudosu_history_user_id'), table_name='kudosu_history')
    op.drop_index(op.f('ix_kudosu_history_created_at'), table_name='kudosu_history')
    op.drop_table('kudosu_history')
    op.drop_table('user_beatmap_favorites')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_beatmaps_status'), table_name='beatmaps')
    op.drop_index(op.f('ix_beatmaps_mode'), table_name='beatmaps')
    op.drop_index(op.f('ix_beatmaps_difficulty_rating'), table_name='beatmaps')
    op.drop_index(op.f('ix_beatmaps_checksum'), table_name='beatmaps')
    op.drop_index(op.f('ix_beatmaps_beatmapset_id'), table_name='beatmaps')
    op.drop_table('beatmaps')
    op.drop_index(op.f('ix_user_statistics_user_id'), table_name='user_statistics')
    op.drop_index(op.f('ix_user_statistics_mode'), table_name='user_statistics')
    op.drop_table('user_statistics')
    op.drop_table('user_relations')
    op.drop_table('user_group_memberships')
    op.drop_table('oauth_clients')
    op.drop_table('multiplayer_rooms')
    op.drop_table('matchmaking_user_stats')
    op.drop_index(op.f('ix_matchmaking_user_elo_history_user_id'), table_name='matchmaking_user_elo_history')
    op.drop_index(op.f('ix_matchmaking_user_elo_history_pool_id'), table_name='matchmaking_user_elo_history')
    op.drop_index(op.f('ix_matchmaking_user_elo_history_opponent_id'), table_name='matchmaking_user_elo_history')
    op.drop_table('matchmaking_user_elo_history')
    op.drop_index(op.f('ix_beatmapsets_status'), table_name='beatmapsets')
    op.drop_table('beatmapsets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('osu_builds')
    op.drop_table('matchmaking_pools')
    op.drop_table('chat_filters')
    # ### end Alembic commands ###
