"""sync db

Revision ID: 665b7301e6fd
Revises: b9111fe8133c
Create Date: 2026-04-05 15:33:54.493797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '665b7301e6fd'
down_revision: Union[str, Sequence[str], None] = 'b9111fe8133c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_osu_user_banhistory_timestamp'), table_name='osu_user_banhistory')
    op.drop_table('osu_user_banhistory', if_exists=True)
    op.create_unique_constraint('uq_matchmaking_user_stats_user_pool', 'matchmaking_user_stats', ['user_id', 'pool_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_matchmaking_user_stats_user_pool', 'matchmaking_user_stats', type_='unique')
    op.create_table('osu_user_banhistory',
    sa.Column('ban_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ban_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permanent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ban_id', name=op.f('osu_user_banhistory_pkey'))
    )
    op.create_index(op.f('ix_osu_user_banhistory_timestamp'), 'osu_user_banhistory', ['timestamp'], unique=False)
    # ### end Alembic commands ###
