"""Update new schema

Revision ID: 7164450729c7
Revises: 
Create Date: 2026-03-31 22:33:49.581107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7164450729c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplayer_scores_high', if_exists=True)
    op.add_column('score_tokens', sa.Column('playlist_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_score_tokens_playlist_item_id'), 'score_tokens', ['playlist_item_id'], unique=False)
    op.create_foreign_key(None, 'score_tokens', 'multiplayer_playlist_items', ['playlist_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_score_tokens_playlist_item_id'), table_name='score_tokens')
    op.drop_column('score_tokens', 'playlist_item_id')
    op.create_table('multiplayer_scores_high',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('playlist_item_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_item_id'], ['multiplayer_playlist_items.id'], name=op.f('multiplayer_scores_high_playlist_item_id_fkey')),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], name=op.f('multiplayer_scores_high_score_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('multiplayer_scores_high_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('multiplayer_scores_high_pkey')),
    sa.UniqueConstraint('playlist_item_id', 'user_id', name=op.f('multiplayer_scores_high_playlist_item_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
