"""Update_hubs_compact

Revision ID: b9111fe8133c
Revises: 7164450729c7
Create Date: 2026-04-01 21:13:48.882292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9111fe8133c'
down_revision: Union[str, Sequence[str], None] = '7164450729c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'uq_matchmaking_user_stats_user_pool'
            ) THEN
                ALTER TABLE matchmaking_user_stats
                ADD CONSTRAINT uq_matchmaking_user_stats_user_pool
                UNIQUE (user_id, pool_id);
            END IF;
        END$$;
        """)
    op.add_column('users', sa.Column('hide_presence', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('allow_pm_from_non_friends', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allow_pm_from_non_friends')
    op.drop_column('users', 'hide_presence')
    op.drop_constraint('uq_matchmaking_user_stats_user_pool', 'matchmaking_user_stats', type_='unique')
    # ### end Alembic commands ###
